In [16]:
# Dependencies
import pandas as pd
from sqlalchemy import create_engine
import csv
import os
import numpy as np
from chardet import detect
from pymongo import MongoClient
from bson import json_util
from pprint import pprint


MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
DB_NAME = 'ETL_Project'
COLLECTION_NAME = 'GDP_pop'

In [2]:
# Store filepath in a variable
#file_one= "Resources/gtd_14to17_0718dist.csv"
#file_two="Resources/gtd_96to13_0718dist.csv"
file_three = "Resources/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_10473720.csv"
file_four = "Resources/API_SP.POP.TOTL_DS2_en_csv_v2_10473719.csv"

In [3]:
GDP_df = pd.read_csv(file_three, encoding='ISO-8859-1', delimiter='\t')
GDP_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,24630.939270,23512.602600,24984.279450,24709.602260,25018.308950,25528.403780,25796.380250,25251.639680,25655.102020,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,...,444.184404,550.514974,599.297630,648.511070,647.966461,625.339539,590.076474,549.582760,550.068459,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3117.896944,3585.905553,4615.867475,5102.489969,5258.407376,5412.692348,4170.730358,3509.604211,4100.289786,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4114.134899,4094.360204,4437.177794,4247.614342,4413.082887,4578.667934,3952.830781,4131.872341,4537.579056,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,43339.379870,39736.354060,41098.766940,38391.080870,40619.711300,42294.994730,36038.267600,37231.815670,39146.548840,NaN

In [4]:
#file_one_df = pd.read_csv(file_one)
#file_two_df = pd.read_csv(file_two)
# file_three_df = pd.read_csv(file_three, sep='')

# import chardet

# f = open(file_four, 'r')
# for line in f:
#     print(chardet.detect(str.encode(line))['encoding'])



pop_df = pd.read_csv(file_four, encoding='ISO-8859-1', delimiter='\t')
pop_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,...,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,...,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,...,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,...,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0,NaN

In [5]:
# Merge the first two datasets on "country" 
GDP_pop_df = pd.merge(GDP_df, pop_df, how='outer', on='Country Name')
GDP_pop_df.head()

,Country Name,Country Code_x,Indicator Name_x,Indicator Code_x,1960_x,1961_x,1962_x,1963_x,1964_x,1965_x,...,2009_y,2010_y,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,...,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0,NaN

In [6]:
GDP_pop_df.drop(columns=['Indicator Name_x', 'Indicator Code_x'])

,Country Name,Country Code_x,1960_x,1961_x,1962_x,1963_x,1964_x,1965_x,1966_x,1967_x,...,2009_y,2010_y,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05,NaN
1,Afghanistan,AFG,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,137.899362,161.322000,...,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,3.553008e+07,NaN
2,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,2.978419e+07,NaN
3,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,2.873457e+06,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04,NaN
5,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08,NaN
6,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,9.400145e+06,NaN
7,Argentina,ARG,NaN,NaN,1148.579957,845.077184,1166.317400,1272.010496,1266.344989,1057.755661,...,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,4.427104e+07,NaN
8,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,2.930450e+06,NaN
9,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04,NaN
10,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05,NaN
11,Australia,AUS,1807.349784,1874.304768,1851.424816,1963.639079,2127.566902,2277.066676,2339.861938,2575.620077,...,2.169170e+07,2.203175e+07,2.234002e+07,2.274248e+07,2.314590e+07,2.350414e+07,2.385078e+07,2.421081e+07,2.459893e+07,NaN
12,Austria,AUT,935.460427,1031.815004,1087.834243,1167.000532,1269.412583,1374.532140,1486.968606,1569.667183,...,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.809212e+06,NaN
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.757812e+06,9.862429e+06,NaN
14,Burundi,BDI,70.349079,71.487278,73.781765,78.900284,86.603195,51.657365,52.476723,55.131687,...,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,1.086424e+07,NaN
15,Belgium,BEL,1273.691659,1350.197673,1438.523233,1535.023729,1701.846276,1835.594766,1957.626080,2086.636005,...,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137207e+07,NaN
16,Benin,BEN,93.022509,95.572155,94.464535,99.859114,104.339768,110.132794,112.940836,111.951602,...,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,1.117569e+07,NaN
17,Burkina Faso,BFA,68.424749,71.558180,76.520611,78.372072,80.472767,81.725116,82.545637,84.363165,...,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,1.919338e+07,NaN
18,Bangladesh,BGD,88.691211,97.142730,99.576714,101.260491,99.503864,105.789170,111.658640,121.662093,...,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,1.646698e+08,NaN
19,Bulgaria,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075991e+06,NaN
20,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,1.492584e+06,NaN
21,"Bahamas, The",BHS,1550.324315,1651.475477,1752.970293,1867.112988,1994.544920,2144.830971,2322.943853,2556.835301,...,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,3.953610e+05,NaN
22,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,3.507017e+06,NaN
23,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.501534e+06,9.507875e+06,NaN
24,Belize,BLZ,304.917107,316.403606,327.126868,336.941466,351.161126,377.594305,406.097967,420.431888,...,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,3.746810e+05,NaN
25,Bermuda,BMU,1902.402119,1961.538169,2020.385965,2020.265248,2199.727007,2282.216546,2630.850466,2982.749704,...,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04,NaN
26,Bolivia,BOL,101.227704,108.022520,115.855641,122.350540,135.181861,148.474080,161.147465,178.377575,...,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,1.105160e+07,NaN
27,Brazil,BRA,210.027470,204.929301,260.225266,291.950589,261.331083,260.964692,315.277382,346.880100,...,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,2.092883e+08,NaN
28,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,2.857190e+05,NaN
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,1113.402447,1237.079237,1235.892097,...,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,4.286970e+05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,364.627854,374.939363,417.369942,408.597891,443.086920,459.037415,490.081748,488.622224,...,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,6.280598e+08,NaN
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,1.296311e+06,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,3.752170e+08,NaN
237,Tonga,TON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,1.080200e+05,NaN
238,South Asia (IDA & IBRD),TSA,81.560979,85.203410,89.011798,97.961148,109.756897,115.384173,94.887667,102.144802,...,1.607664e+09,1.630807e+09,1.653799e+09,1.676615e+09,1.699310e+09,1.721848e+09,1.744200e+09,1.766394e+09,1.788389e+09,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,129.952986,131.935170,139.612810,156.241368,148.741801,161.640459,170.153133,163.908248,...,8.539537e+08,8.776284e+08,9.019899e+08,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09,NaN
240,Trinidad and Tobago,TTO,631.329859,675.974402,703.753422,759.868843,788.124732,807.272181,786.752120,822.955036,...,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,1.369125e+06,NaN
241,Tunisia,TUN,NaN,NaN,NaN,NaN,NaN,218.036019,224.426620,229.168376,...,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,1.153213e+07,NaN
242,Turkey,TUR,509.424112,285.012709,309.446903,350.663223,369.583786,385.640976,445.250492,482.378394,...,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,8.074502e+07,NaN
243,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04,NaN
244,Tanzania,TZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,5.731002e+07,NaN
245,Uganda,UGA,62.315122,63.015161,62.016821,68.935251,76.044610,110.410491,111.635755,112.770493,...,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,4.286296e+07,NaN
246,Ukraine,UKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,4.483116e+07,NaN
247,Upper middle income,UMC,162.277929,147.322109,152.192318,163.881035,175.714323,190.491344,206.591010,209.526909,...,2.422394e+09,2.440543e+09,2.459176e+09,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576203e+09,NaN
248,Uruguay,URY,489.350147,601.701131,656.712218,584.290747,741.243051,701.704718,664.438377,580.969836,...,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,3.456750e+06,NaN
249,United States,USA,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,3827.527110,4146.316646,4336.426587,...,3.067715e+08,3.093384e+08,3.116443e+08,3.139933e+08,3.162345e+08,3.186225e+08,3.210398e+08,3.234059e+08,3.257192e+08,NaN
250,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184790e+07,3.238720e+07,NaN
251,St. Vincent and the Grenadines,VCT,161.417161,170.435141,174.565283,162.869285,173.485175,175.738135,185.360602,180.486664,...,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,1.098970e+05,NaN
252,"Venezuela, RB",VEN,954.859089,967.784893,1017.789558,1068.232259,854.696370,857.815978,863.018429,878.604916,...,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,3.197706e+07,NaN
253,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04,NaN
254,Virgin Islands (U.S.),VIR,744.615385,749.271137,1054.285714,1040.201005,1318.627451,1528.735632,1820.346320,2350.305499,...,1.084050e+05,1.083580e+05,1.082920e+05,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05,NaN
255,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.756541e+07,8.847251e+07,8.943664e+07,9.045188e+07,9.149772e+07,9.254492e+07,9.357157e+07,9.456907e+07,9.554080e+07,NaN
256,Vanuatu,VUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,2.762440e+05,NaN
257,World,WLD,450.480281,462.296648,487.882090,514.576605,552.501112,589.405167,626.259847,653.005696,...,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09,NaN
258,Samoa,WSM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,1.964400e+05,NaN
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,1.830700e+06,NaN
260,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,2.825042e+07,NaN
261,South Africa,ZAF,433.941194,444.896268,461.798232,498.601747,534.374176,568.348265,603.069811,654.626304,...,5.097082e+07,5.158466e+07,5.226352e+07,5.299821e+07,5.376740e+07,5.453957e+07,5.529122e+07,5.601547e+07,5.671716e+07,NaN
262,Zambia,ZMB,234.166194,221.728401,213.894229,214.852954,243.105321,303.882532,343.912055,360.770244,...,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,1.709413e+07,NaN
263,Zimbabwe,ZWE,280.994586,283.315869,279.440989,280.566213,285.053174,297.363437,281.490800,297.231875,...,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07,NaN

In [7]:
t = iter(range(1, 61))
# dataframe.columns = ['x'.format(next(t)) if 100 <= i <= 499 else x for i, x in enumerate(dataframe.columns, 1)]

#ames = list(GDP_pop_df.columns.values)

# new_names = [x.replace('_x',' GDP').replace('_y',' POP') for x in names]

names={}

for year in range(1960, 2019):
    names[f"{year}_x"] = f"{year} GDP"
    names[f"{year}_y"] = f"{year} pop"
print(names)

# GDP_pop_df.columns = new_names
#GDP_pop_df = GDP_pop_df.columns

{'1960_x': '1960 GDP', '1960_y': '1960 pop', '1961_x': '1961 GDP', '1961_y': '1961 pop', '1962_x': '1962 GDP', '1962_y': '1962 pop', '1963_x': '1963 GDP', '1963_y': '1963 pop', '1964_x': '1964 GDP', '1964_y': '1964 pop', '1965_x': '1965 GDP', '1965_y': '1965 pop', '1966_x': '1966 GDP', '1966_y': '1966 pop', '1967_x': '1967 GDP', '1967_y': '1967 pop', '1968_x': '1968 GDP', '1968_y': '1968 pop', '1969_x': '1969 GDP', '1969_y': '1969 pop', '1970_x': '1970 GDP', '1970_y': '1970 pop', '1971_x': '1971 GDP', '1971_y': '1971 pop', '1972_x': '1972 GDP', '1972_y': '1972 pop', '1973_x': '1973 GDP', '1973_y': '1973 pop', '1974_x': '1974 GDP', '1974_y': '1974 pop', '1975_x': '1975 GDP', '1975_y': '1975 pop', '1976_x': '1976 GDP', '1976_y': '1976 pop', '1977_x': '1977 GDP', '1977_y': '1977 pop', '1978_x': '1978 GDP', '1978_y': '1978 pop', '1979_x': '1979 GDP', '1979_y': '1979 pop', '1980_x': '1980 GDP', '1980_y': '1980 pop', '1981_x': '1981 GDP', '1981_y': '1981 pop', '1982_x': '1982 GDP', '1982_y': '1982 pop', '1983_x': '1983 GDP', '1983_y': '1983 pop', '1984_x': '1984 GDP', '1984_y': '1984 pop', '1985_x': '1985 GDP', '1985_y': '1985 pop', '1986_x': '1986 GDP', '1986_y': '1986 pop', '1987_x': '1987 GDP', '1987_y': '1987 pop', '1988_x': '1988 GDP', '1988_y': '1988 pop', '1989_x': '1989 GDP', '1989_y': '1989 pop', '1990_x': '1990 GDP', '1990_y': '1990 pop', '1991_x': '1991 GDP', '1991_y': '1991 pop', '1992_x': '1992 GDP', '1992_y': '1992 pop', '1993_x': '1993 GDP', '1993_y': '1993 pop', '1994_x': '1994 GDP', '1994_y': '1994 pop', '1995_x': '1995 GDP', '1995_y': '1995 pop', '1996_x': '1996 GDP', '1996_y': '1996 pop', '1997_x': '1997 GDP', '1997_y': '1997 pop', '1998_x': '1998 GDP', '1998_y': '1998 pop', '1999_x': '1999 GDP', '1999_y': '1999 pop', '2000_x': '2000 GDP', '2000_y': '2000 pop', '2001_x': '2001 GDP', '2001_y': '2001 pop', '2002_x': '2002 GDP', '2002_y': '2002 pop', '2003_x': '2003 GDP', '2003_y': '2003 pop', '2004_x': '2004 GDP', '2004_y': '2004 pop', '2005_x': '2005 GDP', '2005_y': '2005 pop', '2006_x': '2006 GDP', '2006_y': '2006 pop', '2007_x': '2007 GDP', '2007_y': '2007 pop', '2008_x': '2008 GDP', '2008_y': '2008 pop', '2009_x': '2009 GDP', '2009_y': '2009 pop', '2010_x': '2010 GDP', '2010_y': '2010 pop', '2011_x': '2011 GDP', '2011_y': '2011 pop', '2012_x': '2012 GDP', '2012_y': '2012 pop', '2013_x': '2013 GDP', '2013_y': '2013 pop', '2014_x': '2014 GDP', '2014_y': '2014 pop', '2015_x': '2015 GDP', '2015_y': '2015 pop', '2016_x': '2016 GDP', '2016_y': '2016 pop', '2017_x': '2017 GDP', '2017_y': '2017 pop', '2018_x': '2018 GDP', '2018_y': '2018 pop'}

In [8]:
# Rename our _x columns to "1960 GDP", "1960 Pop"
GDP_pop_df = GDP_pop_df.rename(columns=names)
GDP_pop_df.head()

,Country Name,Country Code_x,Indicator Name_x,Indicator Code_x,1960 GDP,1961 GDP,1962 GDP,1963 GDP,1964 GDP,1965 GDP,...,2009 pop,2010 pop,2011 pop,2012 pop,2013 pop,2014 pop,2015 pop,2016 pop,2017 pop,2018 pop
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,...,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0,NaN

In [32]:
GDP_pop_df.drop(columns=['Indicator Name_x', 'Indicator Code_x'])

NameError: name 'GDP_pop_df' is not defined

In [31]:
client = MongoClient('mongodb://localhost:27017')
db = client.ETL_Project

WGI = db.WGI.find_one()
GDP = db.GDP_pop.find_one()
Ter= db.Terrorism_Records.find_one()

pprint(WGI)

{'1996COC': '',
 '1996GE': '',
 '1996PSNV': '',
 '1996ROL': '',
 '1996RQ': '',
 '1996VAA': '',
 '1998COC': '',
 '1998GE': '',
 '1998PSNV': '',
 '1998ROL': '',
 '1998RQ': '',
 '1998VAA': '',
 '2000COC': '',
 '2000GE': '',
 '2000PSNV': '',
 '2000ROL': '',
 '2000RQ': '',
 '2000VAA': '',
 '2002COC': '',
 '2002GE': '',
 '2002PSNV': '',
 '2002ROL': '',
 '2002RQ': '',
 '2002VAA': '',
 '2003COC': '',
 '2003GE': '',
 '2003PSNV': '',
 '2003ROL': '',
 '2003RQ': '',
 '2003VAA': '',
 '2004COC': '1.18',
 '2004GE': '1.3',
 '2004PSNV': '0.99',
 '2004ROL': '0.93',
 '2004RQ': '0.77',
 '2004VAA': '0.74',
 '2005COC': '1.28',
 '2005GE': '1.29',
 '2005PSNV': '1.38',
 '2005ROL': '0.86',
 '2005RQ': '0.87',
 '2005VAA': '1.15',
 '2006COC': '1.26',
 '2006GE': '1.29',
 '2006PSNV': '1.31',
 '2006ROL': '0.82',
 '2006RQ': '0.86',
 '2006VAA': '1.02',
 '2007COC': '1.27',
 '2007GE': '1.25',
 '2007PSNV': '1.29',
 '2007ROL': '0.84',
 '2007RQ': '0.88',
 '2007VAA': '0.97',
 '2008COC': '1.29',
 '2008GE': '1.28',
 '2008PSNV': '1.32',
 '2008ROL': '0.86',
 '2008RQ': '0.89',
 '2008VAA': '0.97',
 '2009COC': '1.12',
 '2009GE': '1.5',
 '2009PSNV': '1.12',
 '2009ROL': '1.43',
 '2009RQ': '1.29',
 '2009VAA': '1.25',
 '2010COC': '1.13',
 '2010GE': '1.25',
 '2010PSNV': '1.1',
 '2010ROL': '1.42',
 '2010RQ': '1.35',
 '2010VAA': '1.28',
 '2011COC': '1.11',
 '2011GE': '1.24',
 '2011PSNV': '1.29',
 '2011ROL': '1.33',
 '2011RQ': '1.32',
 '2011VAA': '1.27',
 '2012COC': '1.1',
 '2012GE': '1.25',
 '2012PSNV': '1.26',
 '2012ROL': '1.32',
 '2012RQ': '1.41',
 '2012VAA': '1.28',
 '2013COC': '1.13',
 '2013GE': '1.23',
 '2013PSNV': '1.31',
 '2013ROL': '1.3',
 '2013RQ': '1.43',
 '2013VAA': '1.28',
 '2014COC': '1.02',
 '2014GE': '0.89',
 '2014PSNV': '1.16',
 '2014ROL': '1.04',
 '2014RQ': '1.25',
 '2014VAA': '1.28',
 '2015COC': '1.3',
 '2015GE': '0.88',
 '2015PSNV': '1.23',
 '2015ROL': '1.26',
 '2015RQ': '1.37',
 '2015VAA': '1.27',
 '2016COC': '1.29',
 '2016GE': '0.89',
 '2016PSNV': '1.28',
 '2016ROL': '1.26',
 '2016RQ': '1.35',
 '2016VAA': '1.28',
 '2017COC': '1.29',
 '2017GE': '0.92',
 '2017PSNV': '1.32',
 '2017ROL': '1.33',
 '2017RQ': '1.19',
 '2017VAA': '1.29',
 'Country Code': 'ABW',
 'Country/Territory': 'Aruba',
 '_id': ObjectId('5c716b93b4e2d322b062271b')}

In [25]:
pprint(GDP)

{'1960 GDP': '',
 '1960 pop': 'SP.POP.TOTL',
 '1961 GDP': '',
 '1961 pop': '54211.0',
 '1962 GDP': '',
 '1962 pop': '55438.0',
 '1963 GDP': '',
 '1963 pop': '56225.0',
 '1964 GDP': '',
 '1964 pop': '56695.0',
 '1965 GDP': '',
 '1965 pop': '57032.0',
 '1966 GDP': '',
 '1966 pop': '57360.0',
 '1967 GDP': '',
 '1967 pop': '57715.0',
 '1968 GDP': '',
 '1968 pop': '58055.0',
 '1969 GDP': '',
 '1969 pop': '58386.0',
 '1970 GDP': '',
 '1970 pop': '58726.0',
 '1971 GDP': '',
 '1971 pop': '59063.0',
 '1972 GDP': '',
 '1972 pop': '59440.0',
 '1973 GDP': '',
 '1973 pop': '59840.0',
 '1974 GDP': '',
 '1974 pop': '60243.0',
 '1975 GDP': '',
 '1975 pop': '60528.0',
 '1976 GDP': '',
 '1976 pop': '60657.0',
 '1977 GDP': '',
 '1977 pop': '60586.0',
 '1978 GDP': '',
 '1978 pop': '60366.0',
 '1979 GDP': '',
 '1979 pop': '60103.0',
 '1980 GDP': '',
 '1980 pop': '59980.0',
 '1981 GDP': '',
 '1981 pop': '60096.0',
 '1982 GDP': '',
 '1982 pop': '60567.0',
 '1983 GDP': '',
 '1983 pop': '61345.0',
 '1984 GDP': '',
 '1984 pop': '62201.0',
 '1985 GDP': '',
 '1985 pop': '62836.0',
 '1986 GDP': '6472.502029',
 '1986 pop': '63026.0',
 '1987 GDP': '7885.796545',
 '1987 pop': '62644.0',
 '1988 GDP': '9764.789979000001',
 '1988 pop': '61833.0',
 '1989 GDP': '11392.45581',
 '1989 pop': '61079.0',
 '1990 GDP': '12307.311740000001',
 '1990 pop': '61032.0',
 '1991 GDP': '13496.00339',
 '1991 pop': '62149.0',
 '1992 GDP': '14046.503999999999',
 '1992 pop': '64622.0',
 '1993 GDP': '14936.82704',
 '1993 pop': '68235.0',
 '1994 GDP': '16241.04632',
 '1994 pop': '72504.0',
 '1995 GDP': '16439.356359999998',
 '1995 pop': '76700.0',
 '1996 GDP': '16586.06844',
 '1996 pop': '80324.0',
 '1997 GDP': '17927.74964',
 '1997 pop': '83200.0',
 '1998 GDP': '19078.34319',
 '1998 pop': '85451.0',
 '1999 GDP': '19356.203390000002',
 '1999 pop': '87277.0',
 '2000 GDP': '20620.700630000003',
 '2000 pop': '89005.0',
 '2001 GDP': '20669.03197',
 '2001 pop': '90853.0',
 '2002 GDP': '20436.887130000003',
 '2002 pop': '92898.0',
 '2003 GDP': '20833.761609999998',
 '2003 pop': '94992.0',
 '2004 GDP': '22569.97499',
 '2004 pop': '97017.0',
 '2005 GDP': '23300.03956',
 '2005 pop': '98737.0',
 '2006 GDP': '24045.74942',
 '2006 pop': '100031.0',
 '2007 GDP': '25835.64314',
 '2007 pop': '100832.0',
 '2008 GDP': '27086.03985',
 '2008 pop': '101220.0',
 '2009 GDP': '24630.93927',
 '2009 pop': '101353.0',
 '2010 GDP': '23512.6026',
 '2010 pop': '101453.0',
 '2011 GDP': '24984.27945',
 '2011 pop': '101669.0',
 '2012 GDP': '24709.60226',
 '2012 pop': '102053.0',
 '2013 GDP': '25018.30895',
 '2013 pop': '102577.0',
 '2014 GDP': '25528.40378',
 '2014 pop': '103187.0',
 '2015 GDP': '25796.38025',
 '2015 pop': '103795.0',
 '2016 GDP': '25251.63968',
 '2016 pop': '104341.0',
 '2017 GDP': '25655.10202',
 '2017 pop': '104822.0',
 '2018 GDP': '',
 '2018 pop': '105264.0',
 'Country Code_x': 'ABW',
 'Country Code_y': 'ABW',
 'Country Name': 'Aruba',
 'Indicator Code_x': 'NY.GDP.PCAP.CD',
 'Indicator Code_y': ' total"',
 'Indicator Name_x': 'GDP per capita (current US$)',
 'Indicator Name_y': '"Population',
 '_id': ObjectId('5c716b5eb4e2d322b0622612')}

In [28]:
pprint(Ter)

{'INT_ANY': '0',
 'INT_IDEO': '0',
 'INT_LOG': '0',
 'INT_MISC': '0',
 '_id': ObjectId('5c7165e0b4e2d322b0604f97'),
 'addnotes': '',
 'alternative': '',
 'alternative_txt': '',
 'approxdate': '',
 'attacktype1': '3',
 'attacktype1_txt': 'Bombing/Explosion',
 'attacktype2': '',
 'attacktype2_txt': '',
 'attacktype3': '',
 'attacktype3_txt': '',
 'city': 'Porto-Vecchio',
 'claim2': '',
 'claim3': '',
 'claimed': '',
 'claimmode': '',
 'claimmode2': '',
 'claimmode2_txt': '',
 'claimmode3': '',
 'claimmode3_txt': '',
 'claimmode_txt': '',
 'compclaim': '',
 'corp1': '',
 'corp2': '',
 'corp3': '',
 'country': '69',
 'country_txt': 'France',
 'crit1': '1',
 'crit2': '1',
 'crit3': '1',
 'dbsource': 'PGIS',
 'divert': '',
 'doubtterr': '-9',
 'extended': '0',
 'gname': 'Corsican Separatists',
 'gname2': '',
 'gname3': '',
 'gsubname': '',
 'gsubname2': '',
 'gsubname3': '',
 'guncertain1': '0',
 'guncertain2': '',
 'guncertain3': '',
 'hostkidoutcome': '',
 'hostkidoutcome_txt': '',
 'iday': '0',
 'imonth': '1',
 'individual': '0',
 'ishostkid': '0',
 'iyear': '1996',
 'kidhijcountry': '',
 'latitude': '41.591369',
 'location': '',
 'longitude': '9.278311',
 'motive': '',
 'multiple': '1',
 'natlty1': '69',
 'natlty1_txt': 'France',
 'natlty2': '',
 'natlty2_txt': '',
 'natlty3': '',
 'natlty3_txt': '',
 'ndays': '',
 'nhostkid': '',
 'nhostkidus': '',
 'nhours': '',
 'nkill': '0',
 'nkillter': '',
 'nkillus': '',
 'nperpcap': '',
 'nperps': '',
 'nreleased': '',
 'nwound': '0',
 'nwoundte': '',
 'nwoundus': '',
 'propcomment': '',
 'property': '1',
 'propextent': '',
 'propextent_txt': '',
 'propvalue': '',
 'provstate': 'Corsica',
 'ransom': '0',
 'ransomamt': '',
 'ransomamtus': '',
 'ransomnote': '',
 'ransompaid': '',
 'ransompaidus': '',
 'region': '8',
 'region_txt': 'Western Europe',
 'related': '"199601000001',
 'resolution': '',
 'scite1': '',
 'scite2': '',
 'scite3': '',
 'specificity': '1.00',
 'success': '1',
 'suicide': '0',
 'summary': '',
 'target1': 'OFC Bldgs',
 'target2': '',
 'target3': '',
 'targsubtype1': '',
 'targsubtype1_txt': '',
 'targsubtype2': '',
 'targsubtype2_txt': '',
 'targsubtype3': '',
 'targsubtype3_txt': '',
 'targtype1': '1',
 'targtype1_txt': 'Business',
 'targtype2': '',
 'targtype2_txt': '',
 'targtype3': '',
 'targtype3_txt': '',
 'vicinity': '0.00',
 'weapdetail': 'Explosive',
 'weapsubtype1': '16',
 'weapsubtype1_txt': 'Unknown Explosive Type',
 'weapsubtype2': '',
 'weapsubtype2_txt': '',
 'weapsubtype3': '',
 'weapsubtype3_txt': '',
 'weapsubtype4': '',
 'weapsubtype4_txt': '',
 'weaptype1': '6',
 'weaptype1_txt': 'Explosives',
 'weaptype2': '',
 'weaptype2_txt': '',
 'weaptype3': '',
 'weaptype3_txt': '',
 'weaptype4': '',
 'weaptype4_txt': ''}

#MONGODB_HOST = 'localhost'
#MONGODB_PORT = 27017
#DB_NAME = 'ETL_Project'
#COLLECTION_NAME = 'GDP_pop'

connection = MongoClient.connect('mongodb://127.0.0.1/ETL_Project)
db = connection.db
collection = db.GDP_pop
collection.find_one({"Country Name"})

In [38]:
pd.dataFrame({
    "column": data
})

None

In [ ]:

territory = []
for record in WGI:
    territory.append(record.country)
    pprint(record)