In [2]:
# Dependencies
import pandas as pd
from sqlalchemy import create_engine
import csv
import os
import numpy as np
from chardet import detect

In [3]:
# Store filepath in a variable
VAA_file = "Resources/VoiceandAccountability.csv"
ROL_file = "Resources/RuleofLaw.csv"
RQ_file = "Resources/RegulatoryQuality.csv"
PSNV_file = "Resources/PoliticalStabilityNoViolence.csv"
GE_file = "Resources/GovernmentEffectiveness.csv"
COC_file = "Resources/ControlofCorruption.csv"

In [4]:
VAC_df = pd.read_csv(VAA_file, encoding='ISO-8859-1', delimiter=',')
VAC_df.head()

,Unnamed: 0,Unnamed: 1,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008VAA,2009VAA,2010VAA,2011VAA,2012VAA,2013VAA,2014VAA,2015VAA,2016VAA,2017VAA
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,0.97,1.25,1.28,1.27,1.28,1.28,1.28,1.27,1.28,1.29
2,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.33,1.32,1.32,1.36,1.43,1.41,1.17,1.19,1.18,1.16
3,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.17,-1.38,-1.4,-1.34,-1.27,-1.24,-1.14,-1.12,-1.04,-0.99
4,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.12,-1.13,-1.12,-1.13,-1.08,-1.11,-1.15,-1.18,-1.14,-1.1

In [5]:
renamed_VAC_df = VAC_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})
renamed_VAC_df.head()

,Country/Territory,WBCode,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008VAA,2009VAA,2010VAA,2011VAA,2012VAA,2013VAA,2014VAA,2015VAA,2016VAA,2017VAA
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,0.97,1.25,1.28,1.27,1.28,1.28,1.28,1.27,1.28,1.29
2,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.33,1.32,1.32,1.36,1.43,1.41,1.17,1.19,1.18,1.16
3,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.17,-1.38,-1.4,-1.34,-1.27,-1.24,-1.14,-1.12,-1.04,-0.99
4,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.12,-1.13,-1.12,-1.13,-1.08,-1.11,-1.15,-1.18,-1.14,-1.1

In [6]:
renamed_VAC_df.drop([0])

,Country/Territory,WBCode,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008VAA,2009VAA,2010VAA,2011VAA,2012VAA,2013VAA,2014VAA,2015VAA,2016VAA,2017VAA
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,0.97,1.25,1.28,1.27,1.28,1.28,1.28,1.27,1.28,1.29
2,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.33,1.32,1.32,1.36,1.43,1.41,1.17,1.19,1.18,1.16
3,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.17,-1.38,-1.4,-1.34,-1.27,-1.24,-1.14,-1.12,-1.04,-0.99
4,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.12,-1.13,-1.12,-1.13,-1.08,-1.11,-1.15,-1.18,-1.14,-1.1
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,0.97,0.96,0.99,1.01,1.03,1,NaN,NaN,NaN,NaN
6,Albania,ALB,-0.65,-0.39,-0.29,-0.01,0.07,0.01,0,0.08,...,0.17,0.14,0.12,0.06,0.02,0.05,0.14,0.16,0.17,0.2
7,Netherlands Antilles (former),ANT,NaN,NaN,NaN,NaN,NaN,0.5,0.65,0.55,...,0.53,0.3,0.33,0.34,0.35,0.34,NaN,NaN,NaN,NaN
8,United Arab Emirates,ARE,-0.41,-0.52,-0.52,-0.63,-0.91,-0.69,-0.71,-1,...,-0.91,-0.84,-0.9,-0.9,-1,-1.02,-1.06,-1.11,-1.05,-1.1
9,Argentina,ARG,0.39,0.31,0.42,0.26,0.35,0.36,0.27,0.4,...,0.36,0.28,0.36,0.34,0.3,0.28,0.35,0.41,0.49,0.53
10,Armenia,ARM,-0.57,-0.34,-0.37,-0.44,-0.47,-0.57,-0.59,-0.74,...,-0.86,-0.88,-0.85,-0.69,-0.57,-0.59,-0.56,-0.54,-0.58,-0.56
11,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,0.5,0.65,0.55,...,0.97,0.96,0.99,1.01,1.03,1,NaN,NaN,NaN,NaN
12,Antigua and Barbuda,ATG,0.33,0.34,0.39,0.34,0.32,0.57,0.53,0.63,...,0.57,0.59,0.5,0.51,0.64,0.62,0.56,0.59,0.63,0.61
13,Australia,AUS,1.44,1.41,1.47,1.41,1.44,1.5,1.51,1.38,...,1.37,1.38,1.42,1.45,1.5,1.44,1.36,1.36,1.35,1.38
14,Austria,AUT,1.45,1.35,1.32,1.31,1.34,1.48,1.38,1.37,...,1.36,1.39,1.43,1.4,1.45,1.46,1.39,1.38,1.34,1.34
15,Azerbaijan,AZE,-1.12,-1.02,-0.91,-0.98,-1.04,-1.06,-1.12,-1.28,...,-1.33,-1.26,-1.3,-1.3,-1.3,-1.4,-1.48,-1.55,-1.56,-1.56
16,Burundi,BDI,-1.55,-1.44,-1.49,-1.16,-1.18,-1.28,-0.63,-0.72,...,-0.69,-0.69,-0.94,-0.93,-0.89,-0.95,-1.04,-1.29,-1.56,-1.57
17,Belgium,BEL,1.43,1.34,1.37,1.38,1.48,1.44,1.42,1.34,...,1.32,1.35,1.36,1.33,1.35,1.37,1.37,1.39,1.38,1.38
18,Benin,BEN,0.26,0.43,0.41,0.05,0.19,0.05,-0.03,0.36,...,0.34,0.34,0.31,0.17,0.12,0.16,0.27,0.3,0.42,0.38
19,Burkina Faso,BFA,-0.53,-0.4,-0.23,-0.39,-0.31,-0.43,-0.45,-0.34,...,-0.28,-0.29,-0.25,-0.28,-0.3,-0.26,-0.35,-0.11,0.01,0.06
20,Bangladesh,BGD,-0.06,-0.09,-0.23,-0.43,-0.55,-0.67,-0.57,-0.45,...,-0.44,-0.29,-0.27,-0.32,-0.4,-0.41,-0.47,-0.51,-0.59,-0.62
21,Bulgaria,BGR,0.43,0.44,0.46,0.53,0.55,0.57,0.59,0.58,...,0.58,0.56,0.53,0.45,0.4,0.34,0.37,0.43,0.4,0.38
22,Bahrain,BHR,-0.72,-1.07,-1.06,-0.57,-0.59,-0.56,-0.74,-0.9,...,-0.87,-0.79,-0.97,-1.22,-1.32,-1.32,-1.31,-1.31,-1.37,-1.39
23,"Bahamas, The",BHS,1.1,1.16,1.2,1.19,1.03,0.98,0.94,1.02,...,1.12,1.01,0.99,0.96,0.93,0.92,1.05,0.95,0.85,0.85
24,Bosnia and Herzegovina,BIH,-0.1,-0.01,-0.11,-0.09,0.21,0.17,0.21,0.19,...,0.02,0,-0.08,-0.16,-0.1,-0.12,-0.07,-0.1,-0.13,-0.21
25,Belarus,BLR,-0.82,-0.77,-1.31,-1.45,-1.46,-1.6,-1.77,-1.75,...,-1.59,-1.55,-1.56,-1.66,-1.57,-1.54,-1.44,-1.46,-1.34,-1.36
26,Belize,BLZ,0.82,0.88,0.98,0.8,0.84,0.74,0.69,0.54,...,0.65,0.74,0.69,0.7,0.7,0.71,0.52,0.58,0.57,0.57
27,Bermuda,BMU,1.18,1.17,0.94,1.13,1.2,1.13,1.15,1.02,...,0.97,0.96,0.99,1.01,1.03,1,NaN,NaN,NaN,NaN
28,Bolivia,BOL,0.16,0.35,0.19,0.14,-0.06,-0.17,-0.16,0.08,...,0,0.01,-0.04,-0.07,-0.08,-0.07,-0.03,0,-0.04,-0.03
29,Brazil,BRA,0.24,0.33,0.3,0.47,0.44,0.39,0.46,0.5,...,0.57,0.52,0.57,0.51,0.48,0.42,0.47,0.46,0.45,0.45
30,Barbados,BRB,1.34,1.27,1.26,1.23,1.16,1.1,0.95,1.04,...,0.95,1.13,1.14,1.11,1.13,1.14,1.15,1.1,1.09,1.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Togo,TGO,-0.99,-1.12,-1.13,-1.38,-1.18,-1.23,-1.22,-1.2,...,-0.99,-0.98,-0.95,-0.9,-1,-0.9,-0.77,-0.7,-0.54,-0.62
186,Thailand,THA,0.31,0.38,0.47,0.32,0.22,0.13,-0.1,-0.74,...,-0.53,-0.46,-0.5,-0.41,-0.32,-0.43,-0.87,-0.97,-1.03,-1.05
187,Tajikistan,TJK,-1.65,-1.51,-1.38,-1.11,-1.15,-1.22,-1.27,-1.35,...,-1.36,-1.33,-1.43,-1.38,-1.42,-1.5,-1.5,-1.57,-1.69,-1.72
188,Turkmenistan,TKM,-1.58,-1.66,-1.69,-1.93,-1.96,-1.98,-2,-2.09,...,-2.11,-2.08,-2.04,-2.17,-2.25,-2.22,-2.26,-2.24,-2.17,-2.16
189,Timor-Leste,TMP,-1.72,-1.7,-0.13,0.27,0.17,-0.09,-0.21,0.06,...,0.22,0.1,0.06,0.13,0.1,0.09,0.15,0.19,0.22,0.34
190,Tonga,TON,0.23,0.25,0.22,-0.02,0.06,-0.19,-0.05,-0.03,...,-0.03,-0.05,0.29,0.32,0.34,0.46,0.66,0.66,0.64,0.6
191,Trinidad and Tobago,TTO,0.69,0.84,0.57,0.57,0.61,0.57,0.61,0.61,...,0.53,0.55,0.52,0.52,0.5,0.48,0.47,0.48,0.56,0.55
192,Tunisia,TUN,-0.6,-0.82,-0.81,-0.96,-0.92,-0.87,-0.95,-1.3,...,-1.35,-1.36,-1.42,-0.37,-0.17,-0.08,0.19,0.24,0.3,0.18
193,Turkey,TUR,-0.13,-0.62,-0.29,-0.22,-0.03,0.01,0,-0.06,...,-0.04,-0.06,-0.08,-0.14,-0.21,-0.25,-0.34,-0.37,-0.61,-0.71
194,Tuvalu,TUV,1.29,1.3,1.32,1.18,1.04,0.46,0.59,0.78,...,0.8,0.74,0.72,0.72,0.66,0.71,1.05,1.07,1.08,1.08
195,"Taiwan, China",TWN,0.67,0.77,0.85,0.97,0.9,0.94,0.93,0.7,...,0.72,0.83,0.83,0.84,0.85,0.89,0.88,0.9,1.01,1.01
196,Tanzania,TZA,-0.64,-0.52,-0.47,-0.4,-0.43,-0.53,-0.36,-0.2,...,-0.17,-0.16,-0.13,-0.14,-0.18,-0.2,-0.19,-0.23,-0.23,-0.29
197,Uganda,UGA,-0.89,-0.86,-0.99,-0.93,-0.7,-0.72,-0.6,-0.45,...,-0.51,-0.51,-0.52,-0.53,-0.49,-0.55,-0.58,-0.57,-0.65,-0.59
198,Ukraine,UKR,-0.32,-0.24,-0.61,-0.52,-0.59,-0.67,-0.29,0.05,...,0.09,0.06,-0.08,-0.13,-0.28,-0.32,-0.14,-0.09,0,0.01
199,Uruguay,URY,0.83,0.97,0.99,1.05,0.99,0.84,0.89,1.03,...,1.06,1.11,1.15,1.12,1.06,1.09,1.11,1.14,1.16,1.17
200,United States,USA,1.35,1.34,1.31,1.34,1.34,1.33,1.29,1.1,...,1.14,1.1,1.13,1.13,1.16,1.1,1.07,1.11,1.11,1.05
201,Uzbekistan,UZB,-1.6,-1.76,-1.83,-1.81,-1.76,-1.78,-1.93,-2.07,...,-2.1,-2.1,-2.09,-2.12,-2.03,-1.97,-1.91,-1.96,-1.89,-1.8
202,St. Vincent and the Grenadines,VCT,1.04,1.06,1.06,1.02,1.07,0.68,1.09,1.06,...,1.07,1.03,1.13,1.02,1.02,1.03,1.15,0.97,0.96,0.94
203,"Venezuela, RB",VEN,-0.09,0.11,-0.07,-0.46,-0.44,-0.6,-0.64,-0.62,...,-0.75,-0.85,-0.87,-0.93,-0.91,-0.95,-1.08,-1.09,-1.14,-1.21
204,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,0.76,1.15,0.78,...,0.75,0.74,0.77,0.78,0.8,0.78,NaN,NaN,NaN,NaN
205,Vietnam,VNM,-1.09,-1.35,-1.24,-1.45,-1.47,-1.34,-1.4,-1.54,...,-1.5,-1.48,-1.5,-1.46,-1.42,-1.37,-1.37,-1.36,-1.37,-1.4
206,Vanuatu,VUT,0.63,0.64,0.64,0.81,0.73,0.28,0.2,0.45,...,0.48,0.51,0.5,0.43,0.4,0.44,0.59,0.59,0.66,0.69
207,West Bank and Gaza,WBG,-0.76,-0.72,-0.77,-0.81,-0.85,-0.68,-0.65,-0.43,...,-0.86,-0.95,-0.82,-1.01,-0.94,-0.93,-0.88,-0.99,-1.09,-1.03
208,"Jersey, Channel Islands",JEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.28,1.29,1.28,1.28,1.27,1.28,1.29
209,"Yemen, Rep.",YEM,-0.68,-0.78,-0.8,-1.16,-0.89,-0.97,-1.05,-1.19,...,-1.22,-1.27,-1.33,-1.39,-1.35,-1.33,-1.3,-1.52,-1.69,-1.69
210,Serbia,SRB,-1.22,-0.97,-0.64,0,-0.12,-0.18,-0.21,0.21,...,0.28,0.34,0.29,0.28,0.2,0.29,0.21,0.23,0.2,0.12
211,South Africa,ZAF,0.84,0.85,0.75,0.66,0.7,0.72,0.65,0.65,...,0.58,0.57,0.6,0.59,0.58,0.6,0.64,0.65,0.65,0.64
212,"Congo, Dem. Rep.",ZAR,-1.6,-1.73,-1.73,-1.61,-1.56,-1.7,-1.52,-1.23,...,-1.39,-1.41,-1.41,-1.49,-1.48,-1.46,-1.29,-1.3,-1.39,-1.44
213,Zambia,ZMB,-0.33,-0.48,-0.41,-0.32,-0.37,-0.44,-0.43,-0.21,...,-0.16,-0.3,-0.24,-0.17,-0.13,-0.11,-0.11,-0.07,-0.31,-0.34
214,Zimbabwe,ZWE,-0.61,-0.79,-1.09,-1.36,-1.43,-1.55,-1.67,-1.54,...,-1.55,-1.54,-1.48,-1.46,-1.47,-1.39,-1.26,-1.17,-1.18,-1.2

In [7]:
final_VAC_df = renamed_VAC_df.drop([0])
final_VAC_df.head()

,Country/Territory,WBCode,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008VAA,2009VAA,2010VAA,2011VAA,2012VAA,2013VAA,2014VAA,2015VAA,2016VAA,2017VAA
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,0.97,1.25,1.28,1.27,1.28,1.28,1.28,1.27,1.28,1.29
2,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.33,1.32,1.32,1.36,1.43,1.41,1.17,1.19,1.18,1.16
3,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.17,-1.38,-1.4,-1.34,-1.27,-1.24,-1.14,-1.12,-1.04,-0.99
4,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.12,-1.13,-1.12,-1.13,-1.08,-1.11,-1.15,-1.18,-1.14,-1.1
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,0.97,0.96,0.99,1.01,1.03,1,NaN,NaN,NaN,NaN

In [8]:
ROL_df = pd.read_csv(ROL_file, encoding='ISO-8859-1', delimiter=',')
ROL_df.head()

,Unnamed: 0,Unnamed: 1,1996ROL,1998ROL,2000ROL,2002ROL,2003ROL,2004ROL,2005ROL,2006ROL,...,2008ROL,2009ROL,2010ROL,2011ROL,2012ROL,2013ROL,2014ROL,2015ROL,2016ROL,2017ROL
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.93,0.86,0.82,...,0.86,1.43,1.42,1.33,1.32,1.3,1.04,1.26,1.26,1.33
2,Andorra,ADO,1.16,1.21,1.31,1.25,1.09,1.21,0.98,0.87,...,1.2,1.22,1.2,1.41,1.41,1.41,1.64,1.58,1.58,1.6
3,Afghanistan,AFG,-1.79,-1.74,-1.78,-1.67,-1.55,-1.7,-1.66,-1.86,...,-1.86,-1.85,-1.85,-1.9,-1.64,-1.6,-1.45,-1.5,-1.5,-1.57
4,Angola,AGO,-1.63,-1.7,-1.66,-1.62,-1.52,-1.5,-1.43,-1.3,...,-1.37,-1.23,-1.27,-1.27,-1.27,-1.27,-1.12,-1.08,-1.09,-1.1

In [9]:
renamed_ROL_df = ROL_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})

In [10]:
renamed_ROL_df.drop([0])

,Country/Territory,WBCode,1996ROL,1998ROL,2000ROL,2002ROL,2003ROL,2004ROL,2005ROL,2006ROL,...,2008ROL,2009ROL,2010ROL,2011ROL,2012ROL,2013ROL,2014ROL,2015ROL,2016ROL,2017ROL
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.93,0.86,0.82,...,0.86,1.43,1.42,1.33,1.32,1.3,1.04,1.26,1.26,1.33
2,Andorra,ADO,1.16,1.21,1.31,1.25,1.09,1.21,0.98,0.87,...,1.2,1.22,1.2,1.41,1.41,1.41,1.64,1.58,1.58,1.6
3,Afghanistan,AFG,-1.79,-1.74,-1.78,-1.67,-1.55,-1.7,-1.66,-1.86,...,-1.86,-1.85,-1.85,-1.9,-1.64,-1.6,-1.45,-1.5,-1.5,-1.57
4,Angola,AGO,-1.63,-1.7,-1.66,-1.62,-1.52,-1.5,-1.43,-1.3,...,-1.37,-1.23,-1.27,-1.27,-1.27,-1.27,-1.12,-1.08,-1.09,-1.1
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,1.16,1.64,1.6,...,1.67,1.4,1.38,1.36,1.36,1.37,0.02,-0.04,-0.08,-0.1
6,Albania,ALB,-0.68,-0.92,-1.01,-0.76,-0.72,-0.69,-0.74,-0.68,...,-0.59,-0.5,-0.41,-0.46,-0.52,-0.52,-0.34,-0.33,-0.33,-0.4
7,Netherlands Antilles (former),ANT,NaN,NaN,NaN,NaN,NaN,0.93,0.86,0.82,...,0.73,0.85,0.85,0.84,0.84,0.85,NaN,NaN,NaN,NaN
8,United Arab Emirates,ARE,0.69,0.75,0.68,0.73,0.57,0.44,0.4,0.32,...,0.42,0.4,0.32,0.5,0.54,0.62,0.65,0.64,0.85,0.8
9,Argentina,ARG,0.08,-0.01,-0.15,-0.76,-0.77,-0.81,-0.55,-0.57,...,-0.68,-0.68,-0.59,-0.56,-0.68,-0.71,-0.89,-0.77,-0.39,-0.25
10,Armenia,ARM,-0.47,-0.36,-0.48,-0.42,-0.3,-0.42,-0.4,-0.55,...,-0.34,-0.48,-0.49,-0.44,-0.42,-0.34,-0.37,-0.39,-0.12,-0.16
11,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,0.85,1.12,1.08,...,1.13,1.13,1.12,1.1,1.1,1.11,1.41,1.35,1.34,1.36
12,Antigua and Barbuda,ATG,1.05,1.09,1.06,1.06,1.07,0.92,0.67,0.93,...,0.95,0.98,0.96,0.95,0.95,0.84,-0.18,0.59,0.51,0.44
13,Australia,AUS,1.71,1.8,1.75,1.8,1.88,1.82,1.72,1.77,...,1.77,1.74,1.76,1.74,1.77,1.78,1.92,1.83,1.76,1.68
14,Austria,AUT,1.81,1.85,1.84,1.89,1.89,1.84,1.86,1.91,...,1.92,1.78,1.8,1.8,1.86,1.85,1.95,1.86,1.82,1.81
15,Azerbaijan,AZE,-1.2,-1.14,-1.15,-0.91,-0.84,-0.87,-0.79,-0.89,...,-0.83,-0.88,-0.89,-0.89,-0.83,-0.72,-0.67,-0.67,-0.52,-0.56
16,Burundi,BDI,-1.42,-1.23,-1.35,-1.25,-1.4,-1.54,-1.15,-0.97,...,-1.02,-1.15,-1.2,-1.14,-1.08,-1.07,-0.97,-1.17,-1.46,-1.4
17,Belgium,BEL,1.37,1.25,1.34,1.37,1.37,1.33,1.27,1.24,...,1.35,1.38,1.39,1.42,1.43,1.44,1.52,1.46,1.39,1.34
18,Benin,BEN,0.05,0.04,-0.16,-0.23,-0.38,-0.51,-0.54,-0.53,...,-0.53,-0.65,-0.67,-0.66,-0.59,-0.57,-0.49,-0.54,-0.61,-0.62
19,Burkina Faso,BFA,-0.93,-0.75,-0.62,-0.65,-0.54,-0.57,-0.52,-0.43,...,-0.34,-0.21,-0.19,-0.36,-0.44,-0.53,-0.55,-0.53,-0.45,-0.4
20,Bangladesh,BGD,-0.93,-0.89,-0.91,-0.9,-1.05,-1.02,-0.98,-0.9,...,-0.75,-0.79,-0.8,-0.73,-0.93,-0.87,-0.78,-0.75,-0.66,-0.67
21,Bulgaria,BGR,-0.34,-0.21,-0.12,-0.03,-0.14,-0.11,-0.1,-0.09,...,-0.11,-0.04,-0.07,-0.11,-0.09,-0.1,-0.05,-0.1,-0.06,-0.04
22,Bahrain,BHR,-0.01,0.38,0.3,0.57,0.62,0.71,0.61,0.38,...,0.53,0.52,0.44,0.35,0.26,0.33,0.41,0.43,0.46,0.45
23,"Bahamas, The",BHS,1.15,1.3,1.32,1.43,1.45,1.4,1.38,1.09,...,1.2,0.8,0.72,0.62,0.62,0.64,0.67,0.6,0.26,0.19
24,Bosnia and Herzegovina,BIH,-0.24,-0.64,-0.61,-0.66,-0.63,-0.5,-0.52,-0.5,...,-0.41,-0.36,-0.35,-0.33,-0.21,-0.15,-0.19,-0.28,-0.22,-0.21
25,Belarus,BLR,-0.8,-0.93,-1.13,-1.34,-1.19,-1.26,-1.23,-1.33,...,-1.06,-1.03,-1.07,-1.11,-0.94,-0.9,-0.84,-0.81,-0.72,-0.82
26,Belize,BLZ,0.08,-0.04,0.13,-0.09,0.1,-0.19,-0.16,-0.04,...,-0.21,-0.37,-0.34,-0.49,-0.46,-0.47,-0.75,-0.72,-0.86,-0.96
27,Bermuda,BMU,1.21,1.25,1.26,1.24,1.26,1.11,0.86,0.82,...,0.86,0.86,1.12,1.1,1.1,1.11,0.02,0.88,0.87,0.87
28,Bolivia,BOL,-0.26,-0.22,-0.39,-0.4,-0.45,-0.68,-0.76,-0.85,...,-0.97,-1.11,-1.02,-0.98,-1.02,-1.05,-1.06,-1.14,-1.2,-1.21
29,Brazil,BRA,-0.22,-0.19,-0.21,-0.23,-0.32,-0.36,-0.43,-0.37,...,-0.32,-0.16,0.04,0.04,-0.07,-0.08,-0.05,-0.15,-0.16,-0.28
30,Barbados,BRB,1.05,1.27,1.42,1.52,1.56,1.44,1.35,1.24,...,1.31,1.01,1.08,1.08,1.03,1.05,1.08,1.1,0.8,0.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Togo,TGO,-0.73,-0.73,-0.7,-0.78,-0.93,-1.11,-1.08,-0.94,...,-0.83,-0.88,-0.92,-0.88,-0.93,-0.97,-0.86,-0.8,-0.63,-0.71
186,Thailand,THA,0.54,0.52,0.58,0.38,0.16,0.11,0.05,-0.06,...,-0.14,-0.23,-0.2,-0.2,-0.15,-0.12,-0.19,-0.15,0,0.04
187,Tajikistan,TJK,-1.65,-1.54,-1.39,-1.19,-1.03,-1.17,-1.09,-1.18,...,-1.29,-1.27,-1.21,-1.23,-1.2,-1.25,-1.01,-1.06,-1.15,-1.35
188,Turkmenistan,TKM,-1.49,-1.42,-1.33,-1.41,-1.42,-1.63,-1.61,-1.64,...,-1.47,-1.47,-1.49,-1.46,-1.4,-1.39,-1.36,-1.42,-1.49,-1.49
189,Timor-Leste,TMP,-1.57,-1.57,0.29,-0.83,-0.53,-0.69,-0.5,-1.09,...,-1.05,-1.19,-1.17,-1.18,-1.14,-1.21,-1.12,-1.12,-1.16,-1.17
190,Tonga,TON,0.81,0.18,0.24,0.16,-0.28,0.07,0.53,0.59,...,0.07,-0.09,0.07,-0.02,-0.04,-0.01,-0.15,-0.2,0.26,0.31
191,Trinidad and Tobago,TTO,0.53,0.56,0.45,0.46,0.28,0.02,0,-0.19,...,-0.19,-0.18,-0.17,-0.15,-0.14,-0.17,-0.09,-0.12,-0.15,-0.11
192,Tunisia,TUN,-0.3,-0.24,-0.22,-0.12,-0.14,0.05,-0.01,0.11,...,0.07,0.13,0.06,-0.13,-0.13,-0.19,-0.11,-0.06,0,0.07
193,Turkey,TUR,-0.14,-0.06,-0.01,-0.03,0.15,0.13,0.16,0.05,...,0.08,0.1,0.11,0.07,0.04,0.07,0.01,-0.11,-0.21,-0.25
194,Tuvalu,TUV,0.81,0.91,1.36,1.37,1.3,0.88,1.27,1.09,...,0.99,1.02,1,0.47,0.46,0.49,0.37,0.36,0.47,0.56
195,"Taiwan, China",TWN,0.76,0.77,0.83,0.89,0.98,1,1.03,0.78,...,0.79,0.94,1.01,1.03,1.05,1.05,1.19,1.16,1.14,1.14
196,Tanzania,TZA,-0.19,-0.21,-0.35,-0.34,-0.25,-0.36,-0.28,-0.44,...,-0.35,-0.48,-0.49,-0.51,-0.53,-0.47,-0.4,-0.37,-0.38,-0.45
197,Uganda,UGA,-0.58,-0.53,-0.79,-0.61,-0.49,-0.63,-0.58,-0.33,...,-0.35,-0.41,-0.4,-0.36,-0.35,-0.34,-0.39,-0.39,-0.25,-0.3
198,Ukraine,UKR,-0.82,-1,-1.11,-0.81,-0.78,-0.76,-0.78,-0.8,...,-0.68,-0.76,-0.81,-0.82,-0.78,-0.8,-0.79,-0.81,-0.77,-0.71
199,Uruguay,URY,0.56,0.66,0.59,0.68,0.66,0.46,0.47,0.56,...,0.6,0.72,0.74,0.7,0.59,0.56,0.71,0.71,0.63,0.59
200,United States,USA,1.5,1.61,1.59,1.55,1.59,1.44,1.54,1.61,...,1.64,1.6,1.64,1.6,1.63,1.56,1.61,1.6,1.62,1.64
201,Uzbekistan,UZB,-1.24,-1.28,-1.22,-1.48,-1.31,-1.32,-1.46,-1.45,...,-1.17,-1.32,-1.42,-1.45,-1.29,-1.23,-1.13,-1.11,-1.11,-1.11
202,St. Vincent and the Grenadines,VCT,0.81,0.42,0.85,0.92,0.62,0.72,0.77,0.83,...,0.9,0.89,0.88,0.92,0.91,0.88,0.55,0.59,0.4,0.43
203,"Venezuela, RB",VEN,-0.75,-0.68,-0.86,-1.13,-1.29,-1.24,-1.24,-1.42,...,-1.62,-1.62,-1.65,-1.68,-1.69,-1.82,-1.92,-2.03,-2.24,-2.26
204,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,1.21,1.12,1.08,...,0.86,0.86,0.85,0.84,0.84,0.85,0.02,0.88,0.63,0.63
205,Vietnam,VNM,-0.48,-0.45,-0.36,-0.64,-0.58,-0.57,-0.32,-0.52,...,-0.47,-0.54,-0.59,-0.54,-0.55,-0.51,-0.36,-0.34,0.08,0.07
206,Vanuatu,VUT,0.32,0.01,0.39,0.25,0.11,0.07,0.51,0.55,...,0.46,0.4,0.26,0.27,0.28,0.31,0.18,0.1,0.34,0.49
207,West Bank and Gaza,WBG,-0.04,-0.03,-0.08,-0.33,-0.09,-0.26,-0.34,-0.39,...,-0.76,-0.31,-0.2,-0.43,-0.44,-0.4,-0.39,-0.51,-0.34,-0.42
208,"Jersey, Channel Islands",JEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.74,1.72,1.7,1.74,1.7,1.72,1.72
209,"Yemen, Rep.",YEM,-1.38,-1.32,-1.46,-1.53,-1.21,-1.22,-1.26,-1.04,...,-0.98,-1.09,-1.09,-1.29,-1.27,-1.18,-1.2,-1.27,-1.64,-1.75
210,Serbia,SRB,-1.26,-1.26,-1.27,-0.86,-0.85,-0.72,-0.91,-0.53,...,-0.5,-0.41,-0.37,-0.29,-0.36,-0.33,-0.15,-0.12,-0.16,-0.19
211,South Africa,ZAF,0.09,0.27,0.2,0.13,0.12,0.11,0.11,0.26,...,0.07,0.12,0.14,0.15,0.11,0.16,0.18,0.09,0.12,-0.01
212,"Congo, Dem. Rep.",ZAR,-1.88,-2.13,-1.91,-1.66,-1.68,-1.72,-1.55,-1.62,...,-1.56,-1.63,-1.62,-1.62,-1.66,-1.57,-1.45,-1.57,-1.62,-1.69
213,Zambia,ZMB,-0.53,-0.37,-0.48,-0.31,-0.39,-0.49,-0.52,-0.54,...,-0.41,-0.48,-0.49,-0.46,-0.37,-0.27,-0.24,-0.23,-0.3,-0.33
214,Zimbabwe,ZWE,-0.81,-0.66,-1.34,-1.59,-1.7,-1.8,-1.82,-1.74,...,-1.78,-1.85,-1.82,-1.78,-1.63,-1.58,-1.43,-1.32,-1.37,-1.38

In [11]:
final_ROL_df = renamed_ROL_df.drop([0])
final_ROL_df.head()

,Country/Territory,WBCode,1996ROL,1998ROL,2000ROL,2002ROL,2003ROL,2004ROL,2005ROL,2006ROL,...,2008ROL,2009ROL,2010ROL,2011ROL,2012ROL,2013ROL,2014ROL,2015ROL,2016ROL,2017ROL
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.93,0.86,0.82,...,0.86,1.43,1.42,1.33,1.32,1.3,1.04,1.26,1.26,1.33
2,Andorra,ADO,1.16,1.21,1.31,1.25,1.09,1.21,0.98,0.87,...,1.2,1.22,1.2,1.41,1.41,1.41,1.64,1.58,1.58,1.6
3,Afghanistan,AFG,-1.79,-1.74,-1.78,-1.67,-1.55,-1.7,-1.66,-1.86,...,-1.86,-1.85,-1.85,-1.9,-1.64,-1.6,-1.45,-1.5,-1.5,-1.57
4,Angola,AGO,-1.63,-1.7,-1.66,-1.62,-1.52,-1.5,-1.43,-1.3,...,-1.37,-1.23,-1.27,-1.27,-1.27,-1.27,-1.12,-1.08,-1.09,-1.1
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,1.16,1.64,1.6,...,1.67,1.4,1.38,1.36,1.36,1.37,0.02,-0.04,-0.08,-0.1

In [12]:
RQ_df = pd.read_csv(RQ_file, encoding='ISO-8859-1', delimiter=',')
RQ_df.head()

,Unnamed: 0,Unnamed: 1,1996RQ,1998RQ,2000RQ,2002RQ,2003RQ,2004RQ,2005RQ,2006RQ,...,2008RQ,2009RQ,2010RQ,2011RQ,2012RQ,2013RQ,2014RQ,2015RQ,2016RQ,2017RQ
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.77,0.87,0.86,...,0.89,1.29,1.35,1.32,1.41,1.43,1.25,1.37,1.35,1.19
2,Andorra,ADO,1.27,1.3,1.28,1.47,1.45,1.42,1.36,1.35,...,1.4,1.41,1.39,1.62,1.57,1.57,0.89,0.91,0.87,1.21
3,Afghanistan,AFG,-2.09,-2.09,-2.11,-1.8,-1.43,-1.51,-1.64,-1.67,...,-1.62,-1.67,-1.53,-1.54,-1.19,-1.19,-1.12,-1,-1.33,-1.34
4,Angola,AGO,-1.42,-1.69,-1.8,-1.46,-1.21,-1.25,-1.26,-1.13,...,-1.07,-1.03,-1.04,-1.1,-0.97,-1.05,-0.99,-0.91,-1,-1.04

In [13]:
renamed_RQ_df = RQ_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})

In [14]:
renamed_RQ_df.drop([0])

,Country/Territory,WBCode,1996RQ,1998RQ,2000RQ,2002RQ,2003RQ,2004RQ,2005RQ,2006RQ,...,2008RQ,2009RQ,2010RQ,2011RQ,2012RQ,2013RQ,2014RQ,2015RQ,2016RQ,2017RQ
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.77,0.87,0.86,...,0.89,1.29,1.35,1.32,1.41,1.43,1.25,1.37,1.35,1.19
2,Andorra,ADO,1.27,1.3,1.28,1.47,1.45,1.42,1.36,1.35,...,1.4,1.41,1.39,1.62,1.57,1.57,0.89,0.91,0.87,1.21
3,Afghanistan,AFG,-2.09,-2.09,-2.11,-1.8,-1.43,-1.51,-1.64,-1.67,...,-1.62,-1.67,-1.53,-1.54,-1.19,-1.19,-1.12,-1,-1.33,-1.34
4,Angola,AGO,-1.42,-1.69,-1.8,-1.46,-1.21,-1.25,-1.26,-1.13,...,-1.07,-1.03,-1.04,-1.1,-0.97,-1.05,-0.99,-0.91,-1,-1.04
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.92,1.11,1.35,...,1.4,1.41,1.39,1.37,1.33,1.33,0.89,0.91,0.87,0.84
6,Albania,ALB,-0.47,-0.17,-0.25,-0.22,-0.45,-0.17,-0.37,-0.1,...,0.15,0.24,0.23,0.23,0.2,0.21,0.22,0.19,0.19,0.22
7,Netherlands Antilles (former),ANT,NaN,NaN,NaN,NaN,NaN,0.65,0.87,0.86,...,0.89,0.91,0.89,0.88,0.85,0.85,NaN,NaN,NaN,NaN
8,United Arab Emirates,ARE,0.69,0.62,0.73,1.12,0.67,0.8,0.65,0.63,...,0.57,0.44,0.32,0.45,0.68,0.78,0.99,1.11,0.97,1.01
9,Argentina,ARG,0.52,0.57,0.26,-0.92,-0.71,-0.71,-0.55,-0.64,...,-0.74,-0.85,-0.76,-0.72,-0.93,-0.96,-1.07,-0.91,-0.47,-0.29
10,Armenia,ARM,-0.28,-0.06,-0.12,0.04,0.21,0.13,0.08,0.28,...,0.34,0.3,0.31,0.27,0.35,0.25,0.21,0.24,0.25,0.28
11,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,0.51,0.37,0.36,...,0.39,0.4,0.4,0.39,0.36,0.37,0.18,0.17,0.14,-0.25
12,Antigua and Barbuda,ATG,0.79,0.82,0.79,0.74,0.72,0.59,0.59,0.55,...,0.64,0.65,0.64,0.64,0.6,0.61,0.53,0.37,0.34,0.25
13,Australia,AUS,1.37,1.49,1.64,1.47,1.61,1.72,1.6,1.62,...,1.77,1.82,1.7,1.86,1.79,1.8,1.86,1.79,1.9,1.93
14,Austria,AUT,1.66,1.4,1.53,1.59,1.57,1.52,1.61,1.64,...,1.61,1.45,1.45,1.38,1.52,1.49,1.49,1.4,1.44,1.44
15,Azerbaijan,AZE,-1.2,-0.98,-0.93,-0.71,-0.57,-0.59,-0.58,-0.52,...,-0.35,-0.31,-0.37,-0.37,-0.46,-0.41,-0.28,-0.25,-0.28,-0.25
16,Burundi,BDI,-1.64,-1.54,-1.17,-1.26,-1.17,-1.2,-1.36,-1.2,...,-1.24,-1.16,-1.12,-1.01,-0.95,-0.88,-0.71,-0.71,-0.83,-0.84
17,Belgium,BEL,1.21,1.05,1.2,1.3,1.31,1.36,1.27,1.33,...,1.41,1.31,1.29,1.24,1.23,1.29,1.16,1.29,1.34,1.24
18,Benin,BEN,-0.18,-0.13,-0.17,-0.4,-0.48,-0.48,-0.65,-0.43,...,-0.5,-0.35,-0.33,-0.35,-0.38,-0.4,-0.59,-0.56,-0.53,-0.47
19,Burkina Faso,BFA,-0.3,-0.37,-0.12,-0.11,-0.3,-0.33,-0.4,-0.34,...,-0.19,-0.11,-0.16,-0.18,-0.12,-0.17,-0.31,-0.37,-0.4,-0.44
20,Bangladesh,BGD,-0.93,-0.81,-0.84,-0.98,-0.92,-1.13,-1.07,-1,...,-0.92,-0.86,-0.85,-0.81,-0.95,-0.91,-0.94,-0.9,-0.8,-0.81
21,Bulgaria,BGR,-0.18,0.04,0.2,0.56,0.65,0.66,0.64,0.6,...,0.7,0.67,0.65,0.54,0.56,0.54,0.57,0.56,0.66,0.63
22,Bahrain,BHR,0.79,0.81,0.79,0.91,0.65,0.71,0.66,0.68,...,0.71,0.69,0.71,0.72,0.69,0.61,0.71,0.82,0.61,0.41
23,"Bahamas, The",BHS,0.97,1.06,1.19,1.34,1.19,1.13,1.11,1.05,...,1.05,0.8,0.55,0.53,0.4,0.19,0.17,0.17,0.26,0.12
24,Bosnia and Herzegovina,BIH,-0.91,-0.87,-0.5,-0.56,-0.48,-0.21,-0.58,-0.46,...,-0.15,-0.09,-0.09,-0.03,-0.05,-0.07,-0.09,-0.2,-0.17,-0.15
25,Belarus,BLR,-1.09,-1.77,-1.7,-1.53,-1.3,-1.22,-1.45,-1.62,...,-1.24,-1.12,-1.13,-1.18,-1.07,-1.07,-1.01,-0.99,-0.94,-0.74
26,Belize,BLZ,0.14,0.14,0.02,0.02,0.12,-0.16,0.01,-0.34,...,-0.44,-0.44,-0.41,-0.51,-0.47,-0.48,-0.5,-0.46,-0.51,-0.54
27,Bermuda,BMU,1.51,1.54,1.52,1.47,1.45,1.45,1.36,1.35,...,1.4,1.41,1.39,1.37,1.33,1.33,0.89,0.91,0.87,0.84
28,Bolivia,BOL,0,0.19,0.04,-0.06,-0.08,-0.2,-0.69,-0.89,...,-0.87,-0.88,-0.8,-0.76,-0.82,-0.78,-0.87,-0.89,-0.92,-0.9
29,Brazil,BRA,0.3,0.36,0.36,0.3,0.31,0.03,0.04,-0.03,...,0.05,0.1,0.15,0.17,0.09,0.07,-0.08,-0.19,-0.21,-0.11
30,Barbados,BRB,1.29,1.34,1.31,1.13,1.15,1.09,1.16,1,...,0.88,0.59,0.51,0.65,0.45,0.46,0.34,0.57,0.48,0.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Togo,TGO,-0.39,-0.44,-0.61,-0.69,-0.64,-0.76,-0.79,-0.88,...,-0.95,-0.86,-0.88,-1,-0.84,-0.92,-0.82,-0.82,-0.79,-0.79
186,Thailand,THA,0.06,0.11,0.49,0.18,0.38,0.23,0.47,0.24,...,0.21,0.22,0.17,0.2,0.24,0.23,0.27,0.29,0.17,0.14
187,Tajikistan,TJK,-1.52,-1.35,-1.12,-1.27,-1.06,-1.07,-1.12,-1.11,...,-1.09,-1.07,-1.02,-0.98,-1,-1.06,-1.02,-1.02,-1.09,-1.06
188,Turkmenistan,TKM,-1.38,-1.89,-1.86,-1.91,-1.83,-1.99,-1.85,-2.13,...,-2.02,-1.99,-2.04,-2.02,-2.07,-2.09,-2.06,-2.07,-2.09,-2
189,Timor-Leste,TMP,NaN,NaN,NaN,-1.22,-1.23,-1.11,-1.14,-1.52,...,-1.36,-1.15,-1.11,-1.04,-1.02,-0.98,-0.89,-0.97,-0.98,-0.74
190,Tonga,TON,NaN,-1.14,-0.63,-1.09,-1.16,-0.74,-0.5,-0.67,...,-0.77,-0.58,-0.58,-0.59,-0.63,-0.63,-0.41,-0.42,-0.41,-0.4
191,Trinidad and Tobago,TTO,0.6,0.68,0.67,0.74,0.73,0.66,0.61,0.67,...,0.62,0.56,0.52,0.42,0.24,0.27,0.23,0.15,0.09,0.03
192,Tunisia,TUN,0.14,-0.02,-0.02,-0.12,0.03,-0.09,-0.08,0.11,...,0.06,0,-0.03,-0.19,-0.19,-0.33,-0.38,-0.41,-0.47,-0.41
193,Turkey,TUR,0.1,0.5,0.35,0.1,0.04,0.06,0.28,0.29,...,0.26,0.28,0.3,0.37,0.42,0.43,0.4,0.27,0.2,0.04
194,Tuvalu,TUV,NaN,NaN,0.39,0.3,0.26,-0.04,-0.41,-0.73,...,-1.09,-1.01,-1.15,-1.25,-1.23,-1.3,-0.88,-0.69,-0.59,-0.79
195,"Taiwan, China",TWN,0.87,1.06,1.15,1.05,1.04,1.16,0.93,0.84,...,1,1.04,1.12,1.12,1.19,1.14,1.3,1.35,1.29,1.37
196,Tanzania,TZA,-0.44,-0.4,-0.24,-0.55,-0.5,-0.47,-0.5,-0.39,...,-0.51,-0.44,-0.42,-0.42,-0.39,-0.33,-0.33,-0.37,-0.44,-0.58
197,Uganda,UGA,-0.03,0.2,0.06,-0.04,-0.04,-0.03,-0.27,-0.24,...,-0.23,-0.18,-0.17,-0.16,-0.24,-0.24,-0.22,-0.26,-0.21,-0.22
198,Ukraine,UKR,-0.42,-0.76,-0.53,-0.58,-0.56,-0.4,-0.54,-0.52,...,-0.53,-0.57,-0.52,-0.6,-0.6,-0.62,-0.63,-0.59,-0.43,-0.32
199,Uruguay,URY,0.84,0.84,0.7,0.53,0.31,0.26,0.4,0.37,...,0.26,0.38,0.39,0.44,0.44,0.54,0.53,0.42,0.49,0.66
200,United States,USA,1.59,1.67,1.76,1.6,1.6,1.57,1.61,1.64,...,1.53,1.4,1.45,1.46,1.3,1.27,1.28,1.26,1.5,1.63
201,Uzbekistan,UZB,-1.78,-2.13,-2.1,-1.52,-1.45,-1.62,-1.49,-1.61,...,-1.37,-1.47,-1.55,-1.56,-1.58,-1.6,-1.71,-1.64,-1.62,-1.26
202,St. Vincent and the Grenadines,VCT,NaN,0.3,0.23,0.2,0.24,0.16,1.22,0.89,...,0.54,0.59,0.45,0.42,0.38,0.35,0.36,0.27,0.28,0.25
203,"Venezuela, RB",VEN,-0.31,-0.27,-0.52,-0.64,-1.02,-1.1,-1.11,-1.21,...,-1.39,-1.59,-1.62,-1.48,-1.52,-1.63,-1.82,-1.88,-2,-1.96
204,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,1.28,1.11,0.61,...,0.64,0.65,0.64,0.64,0.6,0.61,0.53,0.54,0.87,0.84
205,Vietnam,VNM,-0.6,-0.69,-0.73,-0.72,-0.56,-0.56,-0.6,-0.62,...,-0.62,-0.62,-0.62,-0.6,-0.67,-0.64,-0.59,-0.48,-0.45,-0.4
206,Vanuatu,VUT,NaN,-0.42,-0.43,-1.1,-1.27,-0.37,0.25,0.01,...,-0.67,-0.66,-0.75,-0.67,-0.73,-0.52,-0.32,-0.35,-0.29,-0.33
207,West Bank and Gaza,WBG,-0.89,-0.88,-0.9,-0.97,-0.99,-0.63,-1.06,-1.01,...,-1.12,-0.21,0.21,0.2,0.08,0.12,0.21,0.1,0.06,0.02
208,"Jersey, Channel Islands",JEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.12,1.16,1.19,1.17,1.14,0.7,0.68
209,"Yemen, Rep.",YEM,-0.44,-0.44,-0.66,-0.8,-0.71,-0.85,-0.83,-0.77,...,-0.72,-0.65,-0.62,-0.84,-0.69,-0.73,-0.89,-1.13,-1.48,-1.45
210,Serbia,SRB,-0.72,-0.82,-0.86,-0.62,-0.59,-0.45,-0.58,-0.44,...,-0.29,-0.13,-0.02,0.03,-0.06,-0.06,0.14,0.16,0.06,0.01
211,South Africa,ZAF,0.52,0.33,0.44,0.66,0.8,0.66,0.7,0.68,...,0.5,0.41,0.36,0.41,0.38,0.42,0.29,0.28,0.21,0.23
212,"Congo, Dem. Rep.",ZAR,-1.76,-2.3,-2.03,-1.47,-1.48,-1.61,-1.68,-1.31,...,-1.3,-1.53,-1.59,-1.52,-1.49,-1.23,-1.36,-1.35,-1.32,-1.47
213,Zambia,ZMB,-0.48,-0.11,-0.26,-0.6,-0.55,-0.54,-0.73,-0.62,...,-0.46,-0.53,-0.5,-0.44,-0.43,-0.47,-0.5,-0.44,-0.48,-0.47
214,Zimbabwe,ZWE,-0.77,-0.7,-1.42,-1.93,-1.98,-2.06,-2.24,-1.96,...,-2.14,-2.12,-2.07,-1.93,-1.89,-1.84,-1.9,-1.65,-1.72,-1.56

In [15]:
final_RQ_df = renamed_RQ_df.drop([0])
final_RQ_df.head()

,Country/Territory,WBCode,1996RQ,1998RQ,2000RQ,2002RQ,2003RQ,2004RQ,2005RQ,2006RQ,...,2008RQ,2009RQ,2010RQ,2011RQ,2012RQ,2013RQ,2014RQ,2015RQ,2016RQ,2017RQ
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.77,0.87,0.86,...,0.89,1.29,1.35,1.32,1.41,1.43,1.25,1.37,1.35,1.19
2,Andorra,ADO,1.27,1.3,1.28,1.47,1.45,1.42,1.36,1.35,...,1.4,1.41,1.39,1.62,1.57,1.57,0.89,0.91,0.87,1.21
3,Afghanistan,AFG,-2.09,-2.09,-2.11,-1.8,-1.43,-1.51,-1.64,-1.67,...,-1.62,-1.67,-1.53,-1.54,-1.19,-1.19,-1.12,-1,-1.33,-1.34
4,Angola,AGO,-1.42,-1.69,-1.8,-1.46,-1.21,-1.25,-1.26,-1.13,...,-1.07,-1.03,-1.04,-1.1,-0.97,-1.05,-0.99,-0.91,-1,-1.04
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.92,1.11,1.35,...,1.4,1.41,1.39,1.37,1.33,1.33,0.89,0.91,0.87,0.84

In [16]:
PSNV_df = pd.read_csv(PSNV_file, encoding='ISO-8859-1', delimiter=',')
PSNV_df.head()

,Unnamed: 0,Unnamed: 1,1996PSNV,1998PSNV,2000PSNV,2002PSNV,2003PSNV,2004PSNV,2005PSNV,2006PSNV,...,2008PSNV,2009PSNV,2010PSNV,2011PSNV,2012PSNV,2013PSNV,2014PSNV,2015PSNV,2016PSNV,2017PSNV
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.99,1.38,1.31,...,1.32,1.12,1.1,1.29,1.26,1.31,1.16,1.23,1.28,1.32
2,Andorra,ADO,1.17,1.18,1.17,1.28,1.46,1.4,1.38,1.35,...,1.34,1.3,1.28,1.3,1.29,1.28,1.29,1.39,1.41,1.45
3,Afghanistan,AFG,-2.41,-2.42,-2.44,-2.04,-2.2,-2.3,-2.07,-2.22,...,-2.69,-2.71,-2.58,-2.5,-2.42,-2.52,-2.41,-2.57,-2.67,-2.78
4,Angola,AGO,-2.06,-2.31,-2.04,-1.58,-1.01,-1.06,-0.89,-0.54,...,-0.36,-0.35,-0.23,-0.37,-0.39,-0.39,-0.33,-0.5,-0.32,-0.29

In [17]:
renamed_PSNV_df = PSNV_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})

In [18]:
final_PSNV_df = renamed_PSNV_df.drop([0])
final_PSNV_df.head()

,Country/Territory,WBCode,1996PSNV,1998PSNV,2000PSNV,2002PSNV,2003PSNV,2004PSNV,2005PSNV,2006PSNV,...,2008PSNV,2009PSNV,2010PSNV,2011PSNV,2012PSNV,2013PSNV,2014PSNV,2015PSNV,2016PSNV,2017PSNV
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.99,1.38,1.31,...,1.32,1.12,1.1,1.29,1.26,1.31,1.16,1.23,1.28,1.32
2,Andorra,ADO,1.17,1.18,1.17,1.28,1.46,1.4,1.38,1.35,...,1.34,1.3,1.28,1.3,1.29,1.28,1.29,1.39,1.41,1.45
3,Afghanistan,AFG,-2.41,-2.42,-2.44,-2.04,-2.2,-2.3,-2.07,-2.22,...,-2.69,-2.71,-2.58,-2.5,-2.42,-2.52,-2.41,-2.57,-2.67,-2.78
4,Angola,AGO,-2.06,-2.31,-2.04,-1.58,-1.01,-1.06,-0.89,-0.54,...,-0.36,-0.35,-0.23,-0.37,-0.39,-0.39,-0.33,-0.5,-0.32,-0.29
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.79,1.19,1.11,...,1.12,0.87,1.37,1.55,1.48,1.53,1.16,1.25,1.32,1.36

In [19]:
GE_df = pd.read_csv(GE_file, encoding='ISO-8859-1', delimiter=',')
GE_df.head()

,Unnamed: 0,Unnamed: 1,1996GE,1998GE,2000GE,2002GE,2003GE,2004GE,2005GE,2006GE,...,2008GE,2009GE,2010GE,2011GE,2012GE,2013GE,2014GE,2015GE,2016GE,2017GE
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,1.3,1.29,1.29,...,1.28,1.5,1.25,1.24,1.25,1.23,0.89,0.88,0.89,0.92
2,Andorra,ADO,1.41,1.46,1.45,1.42,1.41,1.52,1.29,1.54,...,1.54,1.54,1.52,1.5,1.53,1.54,1.72,1.79,1.86,1.94
3,Afghanistan,AFG,-2.18,-2.14,-2.23,-1.57,-1.08,-0.89,-1.21,-1.43,...,-1.5,-1.48,-1.45,-1.45,-1.36,-1.38,-1.33,-1.32,-1.22,-1.33
4,Angola,AGO,-0.86,-1.34,-1.46,-1.24,-1.16,-1.31,-1.14,-1.37,...,-1.06,-0.96,-1.12,-1.15,-0.99,-1.22,-1.12,-1,-1.04,-1.03

In [20]:
renamed_GE_df = GE_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})

In [21]:
final_GE_df = renamed_GE_df.drop([0])
final_GE_df.head()

,Country/Territory,WBCode,1996GE,1998GE,2000GE,2002GE,2003GE,2004GE,2005GE,2006GE,...,2008GE,2009GE,2010GE,2011GE,2012GE,2013GE,2014GE,2015GE,2016GE,2017GE
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,1.3,1.29,1.29,...,1.28,1.5,1.25,1.24,1.25,1.23,0.89,0.88,0.89,0.92
2,Andorra,ADO,1.41,1.46,1.45,1.42,1.41,1.52,1.29,1.54,...,1.54,1.54,1.52,1.5,1.53,1.54,1.72,1.79,1.86,1.94
3,Afghanistan,AFG,-2.18,-2.14,-2.23,-1.57,-1.08,-0.89,-1.21,-1.43,...,-1.5,-1.48,-1.45,-1.45,-1.36,-1.38,-1.33,-1.32,-1.22,-1.33
4,Angola,AGO,-0.86,-1.34,-1.46,-1.24,-1.16,-1.31,-1.14,-1.37,...,-1.06,-0.96,-1.12,-1.15,-0.99,-1.22,-1.12,-1,-1.04,-1.03
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,1.08,1.56,1.54,...,1.54,1.54,1.52,1.5,1.53,1.54,0.95,1.01,1.33,0.84

In [22]:
COC_df = pd.read_csv(COC_file, encoding='ISO-8859-1', delimiter=',')
COC_df.head()

,Unnamed: 0,Unnamed: 1,1996COC,1998COC,2000COC,2002COC,2003COC,2004COC,2005COC,2006COC,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
0,Country/Territory,WBCode,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,1.18,1.28,1.26,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
2,Andorra,ADO,1.32,1.38,1.36,1.35,1.38,1.14,1.28,1.26,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
3,Afghanistan,AFG,-1.29,-1.18,-1.3,-1.26,-1.35,-1.35,-1.44,-1.43,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
4,Angola,AGO,-1.17,-1.41,-1.52,-1.18,-1.32,-1.31,-1.3,-1.22,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41

In [23]:
renamed_COC_df = COC_df.rename(columns={"Unnamed: 0":"Country/Territory", "Unnamed: 1":"WBCode"})

In [24]:
final_COC_df = renamed_COC_df.drop([0])
final_COC_df.head()

,Country/Territory,WBCode,1996COC,1998COC,2000COC,2002COC,2003COC,2004COC,2005COC,2006COC,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
1,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,1.18,1.28,1.26,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
2,Andorra,ADO,1.32,1.38,1.36,1.35,1.38,1.14,1.28,1.26,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
3,Afghanistan,AFG,-1.29,-1.18,-1.3,-1.26,-1.35,-1.35,-1.44,-1.43,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
4,Angola,AGO,-1.17,-1.41,-1.52,-1.18,-1.32,-1.31,-1.3,-1.22,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41
5,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.86,1.28,1.26,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24

In [25]:
VAC_ROL_df = pd.merge(final_VAC_df, final_ROL_df, how='outer', on='Country/Territory')
VAC_ROL_df.head()

,Country/Territory,WBCode_x,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008ROL,2009ROL,2010ROL,2011ROL,2012ROL,2013ROL,2014ROL,2015ROL,2016ROL,2017ROL
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,0.86,1.43,1.42,1.33,1.32,1.3,1.04,1.26,1.26,1.33
1,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.2,1.22,1.2,1.41,1.41,1.41,1.64,1.58,1.58,1.6
2,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.86,-1.85,-1.85,-1.9,-1.64,-1.6,-1.45,-1.5,-1.5,-1.57
3,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.37,-1.23,-1.27,-1.27,-1.27,-1.27,-1.12,-1.08,-1.09,-1.1
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,1.67,1.4,1.38,1.36,1.36,1.37,0.02,-0.04,-0.08,-0.1

In [26]:
RQ_PSNV_df = pd.merge(final_RQ_df, final_PSNV_df, how='outer', on='Country/Territory')
RQ_PSNV_df.head()

,Country/Territory,WBCode_x,1996RQ,1998RQ,2000RQ,2002RQ,2003RQ,2004RQ,2005RQ,2006RQ,...,2008PSNV,2009PSNV,2010PSNV,2011PSNV,2012PSNV,2013PSNV,2014PSNV,2015PSNV,2016PSNV,2017PSNV
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.77,0.87,0.86,...,1.32,1.12,1.1,1.29,1.26,1.31,1.16,1.23,1.28,1.32
1,Andorra,ADO,1.27,1.3,1.28,1.47,1.45,1.42,1.36,1.35,...,1.34,1.3,1.28,1.3,1.29,1.28,1.29,1.39,1.41,1.45
2,Afghanistan,AFG,-2.09,-2.09,-2.11,-1.8,-1.43,-1.51,-1.64,-1.67,...,-2.69,-2.71,-2.58,-2.5,-2.42,-2.52,-2.41,-2.57,-2.67,-2.78
3,Angola,AGO,-1.42,-1.69,-1.8,-1.46,-1.21,-1.25,-1.26,-1.13,...,-0.36,-0.35,-0.23,-0.37,-0.39,-0.39,-0.33,-0.5,-0.32,-0.29
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.92,1.11,1.35,...,1.12,0.87,1.37,1.55,1.48,1.53,1.16,1.25,1.32,1.36

In [27]:
GE_COC_df = pd.merge(final_GE_df, final_COC_df, how='outer', on='Country/Territory')
GE_COC_df.head()

,Country/Territory,WBCode_x,1996GE,1998GE,2000GE,2002GE,2003GE,2004GE,2005GE,2006GE,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,1.3,1.29,1.29,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
1,Andorra,ADO,1.41,1.46,1.45,1.42,1.41,1.52,1.29,1.54,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
2,Afghanistan,AFG,-2.18,-2.14,-2.23,-1.57,-1.08,-0.89,-1.21,-1.43,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
3,Angola,AGO,-0.86,-1.34,-1.46,-1.24,-1.16,-1.31,-1.14,-1.37,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,1.08,1.56,1.54,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24

In [28]:
four_df = pd.merge(VAC_ROL_df, RQ_PSNV_df, how='outer', on='Country/Territory')
four_df.head()

,Country/Territory,WBCode_x_x,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008PSNV,2009PSNV,2010PSNV,2011PSNV,2012PSNV,2013PSNV,2014PSNV,2015PSNV,2016PSNV,2017PSNV
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,1.32,1.12,1.1,1.29,1.26,1.31,1.16,1.23,1.28,1.32
1,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.34,1.3,1.28,1.3,1.29,1.28,1.29,1.39,1.41,1.45
2,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-2.69,-2.71,-2.58,-2.5,-2.42,-2.52,-2.41,-2.57,-2.67,-2.78
3,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-0.36,-0.35,-0.23,-0.37,-0.39,-0.39,-0.33,-0.5,-0.32,-0.29
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,1.12,0.87,1.37,1.55,1.48,1.53,1.16,1.25,1.32,1.36

In [29]:
six_df = pd.merge(four_df, GE_COC_df, how='outer', on='Country/Territory')
six_df.head()

,Country/Territory,WBCode_x_x,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
1,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
2,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
3,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24

In [30]:
all_WGI_df = six_df.rename(columns={"WBCode_x_x":"Country Code"})
all_WGI_df.head()

,Country/Territory,Country Code,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
1,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
2,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
3,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24

In [31]:
list(all_WGI_df.columns.values)

['Country/Territory',
 'Country Code',
 '1996VAA',
 '1998VAA',
 '2000VAA',
 '2002VAA',
 '2003VAA',
 '2004VAA',
 '2005VAA',
 '2006VAA',
 '2007VAA',
 '2008VAA',
 '2009VAA',
 '2010VAA',
 '2011VAA',
 '2012VAA',
 '2013VAA',
 '2014VAA',
 '2015VAA',
 '2016VAA',
 '2017VAA',
 'WBCode_y_x',
 '1996ROL',
 '1998ROL',
 '2000ROL',
 '2002ROL',
 '2003ROL',
 '2004ROL',
 '2005ROL',
 '2006ROL',
 '2007ROL',
 '2008ROL',
 '2009ROL',
 '2010ROL',
 '2011ROL',
 '2012ROL',
 '2013ROL',
 '2014ROL',
 '2015ROL',
 '2016ROL',
 '2017ROL',
 'WBCode_x_y',
 '1996RQ',
 '1998RQ',
 '2000RQ',
 '2002RQ',
 '2003RQ',
 '2004RQ',
 '2005RQ',
 '2006RQ',
 '2007RQ',
 '2008RQ',
 '2009RQ',
 '2010RQ',
 '2011RQ',
 '2012RQ',
 '2013RQ',
 '2014RQ',
 '2015RQ',
 '2016RQ',
 '2017RQ',
 'WBCode_y_y',
 '1996PSNV',
 '1998PSNV',
 '2000PSNV',
 '2002PSNV',
 '2003PSNV',
 '2004PSNV',
 '2005PSNV',
 '2006PSNV',
 '2007PSNV',
 '2008PSNV',
 '2009PSNV',
 '2010PSNV',
 '2011PSNV',
 '2012PSNV',
 '2013PSNV',
 '2014PSNV',
 '2015PSNV',
 '2016PSNV',
 '2017PSNV',
 'WBCode_x',
 '1996GE',
 '1998GE',
 '2000GE',
 '2002GE',
 '2003GE',
 '2004GE',
 '2005GE',
 '2006GE',
 '2007GE',
 '2008GE',
 '2009GE',
 '2010GE',
 '2011GE',
 '2012GE',
 '2013GE',
 '2014GE',
 '2015GE',
 '2016GE',
 '2017GE',
 'WBCode_y',
 '1996COC',
 '1998COC',
 '2000COC',
 '2002COC',
 '2003COC',
 '2004COC',
 '2005COC',
 '2006COC',
 '2007COC',
 '2008COC',
 '2009COC',
 '2010COC',
 '2011COC',
 '2012COC',
 '2013COC',
 '2014COC',
 '2015COC',
 '2016COC',
 '2017COC']

In [32]:
final_WGI_df = all_WGI_df.drop(columns=['WBCode_y','WBCode_x','WBCode_y_y','WBCode_x_y','WBCode_y_x'])
final_WGI_df.head()

,Country/Territory,Country Code,1996VAA,1998VAA,2000VAA,2002VAA,2003VAA,2004VAA,2005VAA,2006VAA,...,2008COC,2009COC,2010COC,2011COC,2012COC,2013COC,2014COC,2015COC,2016COC,2017COC
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.74,1.15,1.02,...,1.29,1.12,1.13,1.11,1.1,1.13,1.02,1.3,1.29,1.29
1,Andorra,ADO,1.56,1.53,1.54,1.44,1.42,1.56,1.53,1.33,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24
2,Afghanistan,AFG,-1.91,-2.04,-2.03,-1.43,-1.18,-1.2,-1.13,-1.11,...,-1.64,-1.53,-1.64,-1.58,-1.42,-1.44,-1.35,-1.34,-1.53,-1.52
3,Angola,AGO,-1.58,-1.41,-1.46,-1.24,-1.27,-1.29,-1.23,-1.25,...,-1.28,-1.4,-1.33,-1.34,-1.27,-1.31,-1.44,-1.39,-1.44,-1.41
4,Anguilla,AIA,NaN,NaN,NaN,NaN,NaN,0.85,0.9,1.02,...,1.29,1.33,1.31,1.28,1.27,1.26,1.23,1.22,1.23,1.24

In [33]:
list(final_WGI_df.columns.values)

['Country/Territory',
 'Country Code',
 '1996VAA',
 '1998VAA',
 '2000VAA',
 '2002VAA',
 '2003VAA',
 '2004VAA',
 '2005VAA',
 '2006VAA',
 '2007VAA',
 '2008VAA',
 '2009VAA',
 '2010VAA',
 '2011VAA',
 '2012VAA',
 '2013VAA',
 '2014VAA',
 '2015VAA',
 '2016VAA',
 '2017VAA',
 '1996ROL',
 '1998ROL',
 '2000ROL',
 '2002ROL',
 '2003ROL',
 '2004ROL',
 '2005ROL',
 '2006ROL',
 '2007ROL',
 '2008ROL',
 '2009ROL',
 '2010ROL',
 '2011ROL',
 '2012ROL',
 '2013ROL',
 '2014ROL',
 '2015ROL',
 '2016ROL',
 '2017ROL',
 '1996RQ',
 '1998RQ',
 '2000RQ',
 '2002RQ',
 '2003RQ',
 '2004RQ',
 '2005RQ',
 '2006RQ',
 '2007RQ',
 '2008RQ',
 '2009RQ',
 '2010RQ',
 '2011RQ',
 '2012RQ',
 '2013RQ',
 '2014RQ',
 '2015RQ',
 '2016RQ',
 '2017RQ',
 '1996PSNV',
 '1998PSNV',
 '2000PSNV',
 '2002PSNV',
 '2003PSNV',
 '2004PSNV',
 '2005PSNV',
 '2006PSNV',
 '2007PSNV',
 '2008PSNV',
 '2009PSNV',
 '2010PSNV',
 '2011PSNV',
 '2012PSNV',
 '2013PSNV',
 '2014PSNV',
 '2015PSNV',
 '2016PSNV',
 '2017PSNV',
 '1996GE',
 '1998GE',
 '2000GE',
 '2002GE',
 '2003GE',
 '2004GE',
 '2005GE',
 '2006GE',
 '2007GE',
 '2008GE',
 '2009GE',
 '2010GE',
 '2011GE',
 '2012GE',
 '2013GE',
 '2014GE',
 '2015GE',
 '2016GE',
 '2017GE',
 '1996COC',
 '1998COC',
 '2000COC',
 '2002COC',
 '2003COC',
 '2004COC',
 '2005COC',
 '2006COC',
 '2007COC',
 '2008COC',
 '2009COC',
 '2010COC',
 '2011COC',
 '2012COC',
 '2013COC',
 '2014COC',
 '2015COC',
 '2016COC',
 '2017COC']

In [34]:
final_WGI_df.to_csv('WGI.csv')